INSERT INTO cannabis.paises (id, iso, pais) VALUES (1, 'AF', 'Afganistan');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (2, 'AX', 'Islas Gland');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (3, 'AL', 'Albania');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (4, 'DE', 'Alemania');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (5, 'AD', 'Andorra');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (6, 'AO', 'Angola');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (7, 'AI', 'Anguilla');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (8, 'AQ', 'Antártida');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (9, 'AG', 'Antigua y Barbuda');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (10, 'AN', 'Antillas Holandesas');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (11, 'SA', 'Arabia Saudí');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (12, 'DZ', 'Argelia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (13, 'AR', 'Argentina');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (14, 'AM', 'Armenia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (15, 'AW', 'Aruba');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (16, 'AU', 'Australia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (17, 'AT', 'Austria');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (18, 'AZ', 'Azerbaiyan');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (19, 'BS', 'Bahamas');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (20, 'BH', 'Bahrein');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (21, 'BD', 'Bangladesh');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (22, 'BB', 'Barbados');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (23, 'BY', 'Bielorrusia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (24, 'BE', 'Belgica');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (25, 'BZ', 'Belice');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (26, 'BJ', 'Benin');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (27, 'BM', 'Bermudas');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (28, 'BT', 'Bhutan');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (29, 'BO', 'Bolivia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (30, 'BA', 'Bosnia y Herzegovina');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (31, 'BW', 'Botsuana');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (32, 'BV', 'Isla Bouvet');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (33, 'BR', 'Brasil');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (34, 'BN', 'Brunei');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (35, 'BG', 'Bulgaria');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (36, 'BF', 'Burkina Faso');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (37, 'BI', 'Burundi');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (38, 'CV', 'Cabo Verde');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (39, 'KY', 'Islas Caiman');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (40, 'KH', 'Camboya');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (41, 'CM', 'Camerun');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (42, 'CA', 'Canada');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (43, 'CF', 'Republica Centroafricana');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (44, 'TD', 'Chad');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (45, 'CZ', 'Republica Checa');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (46, 'CL', 'Chile');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (47, 'CN', 'China');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (48, 'CY', 'Chipre');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (49, 'CX', 'Isla de Navidad');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (50, 'VA', 'Ciudad del Vaticano');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (51, 'CC', 'Islas Cocos');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (52, 'CO', 'Colombia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (53, 'KM', 'Comoras');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (54, 'CD', 'Republica Democrática del Congo');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (55, 'CG', 'Congo');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (56, 'CK', 'Islas Cook');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (57, 'KP', 'Corea del Norte');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (58, 'KR', 'Corea del Sur');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (59, 'CI', 'Costa de Marfil');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (60, 'CR', 'Costa Rica');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (61, 'HR', 'Croacia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (62, 'CU', 'Cuba');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (63, 'DK', 'Dinamarca');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (64, 'DM', 'Dominica');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (65, 'DO', 'Republica Dominicana');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (66, 'EC', 'Ecuador');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (67, 'EG', 'Egipto');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (68, 'SV', 'El Salvador');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (69, 'AE', 'Emiratos Arabes Unidos');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (70, 'ER', 'Eritrea');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (71, 'SK', 'Eslovaquia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (72, 'SI', 'Eslovenia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (73, 'ES', 'Spain');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (74, 'UM', 'Islas ultramarinas de Estados Unidos');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (75, 'US', 'Estados Unidos');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (76, 'EE', 'Estonia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (77, 'ET', 'Etiopia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (78, 'FO', 'Islas Feroe');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (79, 'PH', 'Filipinas');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (80, 'FI', 'Finlandia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (81, 'FJ', 'Fiyi');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (82, 'FR', 'Francia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (83, 'GA', 'Gabon');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (84, 'GM', 'Gambia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (85, 'GE', 'Georgia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (86, 'GS', 'Islas Georgias del Sur y Sandwich del Sur');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (87, 'GH', 'Ghana');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (88, 'GI', 'Gibraltar');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (89, 'GD', 'Granada');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (90, 'GR', 'Grecia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (91, 'GL', 'Groenlandia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (92, 'GP', 'Guadalupe');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (93, 'GU', 'Guam');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (94, 'GT', 'Guatemala');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (95, 'GF', 'Guayana Francesa');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (96, 'GN', 'Guinea');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (97, 'GQ', 'Guinea Ecuatorial');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (98, 'GW', 'Guinea-Bissau');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (99, 'GY', 'Guyana');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (100, 'HT', 'Haiti');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (101, 'HM', 'Islas Heard y McDonald');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (102, 'HN', 'Honduras');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (103, 'HK', 'Hong Kong');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (104, 'HU', 'Hungria');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (105, 'IN', 'India');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (106, 'ID', 'Indonesia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (107, 'IR', 'Iran');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (108, 'IQ', 'Iraq');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (109, 'IE', 'Irlanda');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (110, 'IS', 'Islandia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (111, 'IL', 'Israel');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (112, 'IT', 'Italia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (113, 'JM', 'Jamaica');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (114, 'JP', 'Japon');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (115, 'JO', 'Jordania');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (116, 'KZ', 'Kazajstan');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (117, 'KE', 'Kenia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (118, 'KG', 'Kirguistan');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (119, 'KI', 'Kiribati');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (120, 'KW', 'Kuwait');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (121, 'LA', 'Laos');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (122, 'LS', 'Lesotho');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (123, 'LV', 'Letonia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (124, 'LB', 'Libano');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (125, 'LR', 'Liberia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (126, 'LY', 'Libia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (127, 'LI', 'Liechtenstein');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (128, 'LT', 'Lituania');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (129, 'LU', 'Luxemburgo');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (130, 'MO', 'Macao');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (131, 'MK', 'ARY Macedonia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (132, 'MG', 'Madagascar');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (133, 'MY', 'Malasia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (134, 'MW', 'Malawi');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (135, 'MV', 'Maldivas');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (136, 'ML', 'Mali');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (137, 'MT', 'Malta');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (138, 'FK', 'Islas Malvinas');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (139, 'MP', 'Islas Marianas del Norte');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (140, 'MA', 'Marruecos');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (141, 'MH', 'Islas Marshall');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (142, 'MQ', 'Martinica');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (143, 'MU', 'Mauricio');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (144, 'MR', 'Mauritania');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (145, 'YT', 'Mayotte');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (146, 'MX', 'Mexico');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (147, 'FM', 'Micronesia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (148, 'MD', 'Moldavia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (149, 'MC', 'Monaco');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (150, 'MN', 'Mongolia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (151, 'MS', 'Montserrat');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (152, 'MZ', 'Mozambique');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (153, 'MM', 'Myanmar');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (154, 'NA', 'Namibia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (155, 'NR', 'Nauru');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (156, 'NP', 'Nepal');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (157, 'NI', 'Nicaragua');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (158, 'NE', 'Níger');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (159, 'NG', 'Nigeria');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (160, 'NU', 'Niue');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (161, 'NF', 'Isla Norfolk');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (162, 'NO', 'Noruega');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (163, 'NC', 'Nueva Caledonia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (164, 'NZ', 'Nueva Zelanda');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (165, 'OM', 'Omán');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (166, 'NL', 'Paises Bajos');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (167, 'PK', 'Pakistan');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (168, 'PW', 'Palau');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (169, 'PS', 'Palestina');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (170, 'PA', 'Panama');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (171, 'PG', 'Papua Nueva Guinea');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (172, 'PY', 'Paraguay');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (173, 'PE', 'Peru');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (174, 'PN', 'Islas Pitcairn');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (175, 'PF', 'Polinesia Francesa');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (176, 'PL', 'Polonia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (177, 'PT', 'Portugal');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (178, 'PR', 'Puerto Rico');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (179, 'QA', 'Qatar');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (180, 'GB', 'Reino Unido');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (181, 'RE', 'Reunión');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (182, 'RW', 'Ruanda');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (183, 'RO', 'Rumania');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (184, 'RU', 'Rusia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (185, 'EH', 'Sahara Occidental');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (186, 'SB', 'Islas Salomón');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (187, 'WS', 'Samoa');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (188, 'AS', 'Samoa Americana');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (189, 'KN', 'San Cristóbal y Nevis');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (190, 'SM', 'San Marino');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (191, 'PM', 'San Pedro y Miquelón');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (192, 'VC', 'San Vicente y las Granadinas');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (193, 'SH', 'Santa Helena');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (194, 'LC', 'Santa Lucia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (195, 'ST', 'Santo Tome y Príncipe');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (196, 'SN', 'Senegal');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (197, 'CS', 'Serbia y Montenegro');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (198, 'SC', 'Seychelles');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (199, 'SL', 'Sierra Leona');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (200, 'SG', 'Singapur');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (201, 'SY', 'Siria');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (202, 'SO', 'Somalia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (203, 'LK', 'Sri Lanka');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (204, 'SZ', 'Suazilandia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (205, 'ZA', 'Sudafrica');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (206, 'SD', 'Sudan');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (207, 'SE', 'Suecia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (208, 'CH', 'Suiza');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (209, 'SR', 'Surinam');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (210, 'SJ', 'Svalbard y Jan Mayen');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (211, 'TH', 'Tailandia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (212, 'TW', 'Taiwan');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (213, 'TZ', 'Tanzania');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (214, 'TJ', 'Tayikistan');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (215, 'IO', 'Territorio Británico del Oceano Indico');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (216, 'TF', 'Territorios Australes Franceses');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (217, 'TL', 'Timor Oriental');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (218, 'TG', 'Togo');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (219, 'TK', 'Tokelau');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (220, 'TO', 'Tonga');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (221, 'TT', 'Trinidad y Tobago');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (222, 'TN', 'Tunez');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (223, 'TC', 'Islas Turcas y Caicos');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (224, 'TM', 'Turkmenistan');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (225, 'TR', 'Turquia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (226, 'TV', 'Tuvalu');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (227, 'UA', 'Ucrania');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (228, 'UG', 'Uganda');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (229, 'UY', 'Uruguay');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (230, 'UZ', 'Uzbekistan');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (231, 'VU', 'Vanuatu');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (232, 'VE', 'Venezuela');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (233, 'VN', 'Vietnam');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (234, 'VG', 'Islas Virgenes Britanicas');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (235, 'VI', 'Islas Virgenes de los Estados Unidos');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (236, 'WF', 'Wallis y Futuna');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (237, 'YE', 'Yemen');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (238, 'DJ', 'Yibuti');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (239, 'ZM', 'Zambia');
INSERT INTO cannabis.paises (id, iso, pais) VALUES (240, 'ZW', 'Zimbabue');