INSERT INTO cannabis.paises (iso, pais) VALUES ('AF', 'Afganistan');
INSERT INTO cannabis.paises (iso, pais) VALUES ('AX', 'Islas Gland');
INSERT INTO cannabis.paises (iso, pais) VALUES ('AL', 'Albania');
INSERT INTO cannabis.paises (iso, pais) VALUES ('DE', 'Alemania');
INSERT INTO cannabis.paises (iso, pais) VALUES ('AD', 'Andorra');
INSERT INTO cannabis.paises (iso, pais) VALUES ('AO', 'Angola');
INSERT INTO cannabis.paises (iso, pais) VALUES ('AI', 'Anguilla');
INSERT INTO cannabis.paises (iso, pais) VALUES ('AQ', 'Antártida');
INSERT INTO cannabis.paises (iso, pais) VALUES ('AG', 'Antigua y Barbuda');
INSERT INTO cannabis.paises (iso, pais) VALUES ('AN', 'Antillas Holandesas');
INSERT INTO cannabis.paises (iso, pais) VALUES ('SA', 'Arabia Saudí');
INSERT INTO cannabis.paises (iso, pais) VALUES ('DZ', 'Argelia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('AR', 'Argentina');
INSERT INTO cannabis.paises (iso, pais) VALUES ('AM', 'Armenia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('AW', 'Aruba');
INSERT INTO cannabis.paises (iso, pais) VALUES ('AU', 'Australia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('AT', 'Austria');
INSERT INTO cannabis.paises (iso, pais) VALUES ('AZ', 'Azerbaiyan');
INSERT INTO cannabis.paises (iso, pais) VALUES ('BS', 'Bahamas');
INSERT INTO cannabis.paises (iso, pais) VALUES ('BH', 'Bahrein');
INSERT INTO cannabis.paises (iso, pais) VALUES ('BD', 'Bangladesh');
INSERT INTO cannabis.paises (iso, pais) VALUES ('BB', 'Barbados');
INSERT INTO cannabis.paises (iso, pais) VALUES ('BY', 'Bielorrusia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('BE', 'Belgica');
INSERT INTO cannabis.paises (iso, pais) VALUES ('BZ', 'Belice');
INSERT INTO cannabis.paises (iso, pais) VALUES ('BJ', 'Benin');
INSERT INTO cannabis.paises (iso, pais) VALUES ('BM', 'Bermudas');
INSERT INTO cannabis.paises (iso, pais) VALUES ('BT', 'Bhutan');
INSERT INTO cannabis.paises (iso, pais) VALUES ('BO', 'Bolivia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('BA', 'Bosnia y Herzegovina');
INSERT INTO cannabis.paises (iso, pais) VALUES ('BW', 'Botsuana');
INSERT INTO cannabis.paises (iso, pais) VALUES ('BV', 'Isla Bouvet');
INSERT INTO cannabis.paises (iso, pais) VALUES ('BR', 'Brasil');
INSERT INTO cannabis.paises (iso, pais) VALUES ('BN', 'Brunei');
INSERT INTO cannabis.paises (iso, pais) VALUES ('BG', 'Bulgaria');
INSERT INTO cannabis.paises (iso, pais) VALUES ('BF', 'Burkina Faso');
INSERT INTO cannabis.paises (iso, pais) VALUES ('BI', 'Burundi');
INSERT INTO cannabis.paises (iso, pais) VALUES ('CV', 'Cabo Verde');
INSERT INTO cannabis.paises (iso, pais) VALUES ('KY', 'Islas Caiman');
INSERT INTO cannabis.paises (iso, pais) VALUES ('KH', 'Camboya');
INSERT INTO cannabis.paises (iso, pais) VALUES ('CM', 'Camerun');
INSERT INTO cannabis.paises (iso, pais) VALUES ('CA', 'Canada');
INSERT INTO cannabis.paises (iso, pais) VALUES ('CF', 'Republica Centroafricana');
INSERT INTO cannabis.paises (iso, pais) VALUES ('TD', 'Chad');
INSERT INTO cannabis.paises (iso, pais) VALUES ('CZ', 'Republica Checa');
INSERT INTO cannabis.paises (iso, pais) VALUES ('CL', 'Chile');
INSERT INTO cannabis.paises (iso, pais) VALUES ('CN', 'China');
INSERT INTO cannabis.paises (iso, pais) VALUES ('CY', 'Chipre');
INSERT INTO cannabis.paises (iso, pais) VALUES ('CX', 'Isla de Navidad');
INSERT INTO cannabis.paises (iso, pais) VALUES ('VA', 'Ciudad del Vaticano');
INSERT INTO cannabis.paises (iso, pais) VALUES ('CC', 'Islas Cocos');
INSERT INTO cannabis.paises (iso, pais) VALUES ('CO', 'Colombia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('KM', 'Comoras');
INSERT INTO cannabis.paises (iso, pais) VALUES ('CD', 'Republica Democrática del Congo');
INSERT INTO cannabis.paises (iso, pais) VALUES ('CG', 'Congo');
INSERT INTO cannabis.paises (iso, pais) VALUES ('CK', 'Islas Cook');
INSERT INTO cannabis.paises (iso, pais) VALUES ('KP', 'Corea del Norte');
INSERT INTO cannabis.paises (iso, pais) VALUES ('KR', 'Corea del Sur');
INSERT INTO cannabis.paises (iso, pais) VALUES ('CI', 'Costa de Marfil');
INSERT INTO cannabis.paises (iso, pais) VALUES ('CR', 'Costa Rica');
INSERT INTO cannabis.paises (iso, pais) VALUES ('HR', 'Croacia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('CU', 'Cuba');
INSERT INTO cannabis.paises (iso, pais) VALUES ('DK', 'Dinamarca');
INSERT INTO cannabis.paises (iso, pais) VALUES ('DM', 'Dominica');
INSERT INTO cannabis.paises (iso, pais) VALUES ('DO', 'Republica Dominicana');
INSERT INTO cannabis.paises (iso, pais) VALUES ('EC', 'Ecuador');
INSERT INTO cannabis.paises (iso, pais) VALUES ('EG', 'Egipto');
INSERT INTO cannabis.paises (iso, pais) VALUES ('SV', 'El Salvador');
INSERT INTO cannabis.paises (iso, pais) VALUES ('AE', 'Emiratos Arabes Unidos');
INSERT INTO cannabis.paises (iso, pais) VALUES ('ER', 'Eritrea');
INSERT INTO cannabis.paises (iso, pais) VALUES ('SK', 'Eslovaquia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('SI', 'Eslovenia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('ES', 'Spain');
INSERT INTO cannabis.paises (iso, pais) VALUES ('UM', 'Islas ultramarinas de Estados Unidos');
INSERT INTO cannabis.paises (iso, pais) VALUES ('US', 'Estados Unidos');
INSERT INTO cannabis.paises (iso, pais) VALUES ('EE', 'Estonia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('ET', 'Etiopia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('FO', 'Islas Feroe');
INSERT INTO cannabis.paises (iso, pais) VALUES ('PH', 'Filipinas');
INSERT INTO cannabis.paises (iso, pais) VALUES ('FI', 'Finlandia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('FJ', 'Fiyi');
INSERT INTO cannabis.paises (iso, pais) VALUES ('FR', 'Francia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('GA', 'Gabon');
INSERT INTO cannabis.paises (iso, pais) VALUES ('GM', 'Gambia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('GE', 'Georgia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('GS', 'Islas Georgias del Sur y Sandwich del Sur');
INSERT INTO cannabis.paises (iso, pais) VALUES ('GH', 'Ghana');
INSERT INTO cannabis.paises (iso, pais) VALUES ('GI', 'Gibraltar');
INSERT INTO cannabis.paises (iso, pais) VALUES ('GD', 'Granada');
INSERT INTO cannabis.paises (iso, pais) VALUES ('GR', 'Grecia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('GL', 'Groenlandia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('GP', 'Guadalupe');
INSERT INTO cannabis.paises (iso, pais) VALUES ('GU', 'Guam');
INSERT INTO cannabis.paises (iso, pais) VALUES ('GT', 'Guatemala');
INSERT INTO cannabis.paises (iso, pais) VALUES ('GF', 'Guayana Francesa');
INSERT INTO cannabis.paises (iso, pais) VALUES ('GN', 'Guinea');
INSERT INTO cannabis.paises (iso, pais) VALUES ('GQ', 'Guinea Ecuatorial');
INSERT INTO cannabis.paises (iso, pais) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO cannabis.paises (iso, pais) VALUES ('GY', 'Guyana');
INSERT INTO cannabis.paises (iso, pais) VALUES ('HT', 'Haiti');
INSERT INTO cannabis.paises (iso, pais) VALUES ('HM', 'Islas Heard y McDonald');
INSERT INTO cannabis.paises (iso, pais) VALUES ('HN', 'Honduras');
INSERT INTO cannabis.paises (iso, pais) VALUES ('HK', 'Hong Kong');
INSERT INTO cannabis.paises (iso, pais) VALUES ('HU', 'Hungria');
INSERT INTO cannabis.paises (iso, pais) VALUES ('IN', 'India');
INSERT INTO cannabis.paises (iso, pais) VALUES ('ID', 'Indonesia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('IR', 'Iran');
INSERT INTO cannabis.paises (iso, pais) VALUES ('IQ', 'Iraq');
INSERT INTO cannabis.paises (iso, pais) VALUES ('IE', 'Irlanda');
INSERT INTO cannabis.paises (iso, pais) VALUES ('IS', 'Islandia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('IL', 'Israel');
INSERT INTO cannabis.paises (iso, pais) VALUES ('IT', 'Italia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('JM', 'Jamaica');
INSERT INTO cannabis.paises (iso, pais) VALUES ('JP', 'Japon');
INSERT INTO cannabis.paises (iso, pais) VALUES ('JO', 'Jordania');
INSERT INTO cannabis.paises (iso, pais) VALUES ('KZ', 'Kazajstan');
INSERT INTO cannabis.paises (iso, pais) VALUES ('KE', 'Kenia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('KG', 'Kirguistan');
INSERT INTO cannabis.paises (iso, pais) VALUES ('KI', 'Kiribati');
INSERT INTO cannabis.paises (iso, pais) VALUES ('KW', 'Kuwait');
INSERT INTO cannabis.paises (iso, pais) VALUES ('LA', 'Laos');
INSERT INTO cannabis.paises (iso, pais) VALUES ('LS', 'Lesotho');
INSERT INTO cannabis.paises (iso, pais) VALUES ('LV', 'Letonia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('LB', 'Libano');
INSERT INTO cannabis.paises (iso, pais) VALUES ('LR', 'Liberia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('LY', 'Libia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('LI', 'Liechtenstein');
INSERT INTO cannabis.paises (iso, pais) VALUES ('LT', 'Lituania');
INSERT INTO cannabis.paises (iso, pais) VALUES ('LU', 'Luxemburgo');
INSERT INTO cannabis.paises (iso, pais) VALUES ('MO', 'Macao');
INSERT INTO cannabis.paises (iso, pais) VALUES ('MK', 'ARY Macedonia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('MG', 'Madagascar');
INSERT INTO cannabis.paises (iso, pais) VALUES ('MY', 'Malasia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('MW', 'Malawi');
INSERT INTO cannabis.paises (iso, pais) VALUES ('MV', 'Maldivas');
INSERT INTO cannabis.paises (iso, pais) VALUES ('ML', 'Mali');
INSERT INTO cannabis.paises (iso, pais) VALUES ('MT', 'Malta');
INSERT INTO cannabis.paises (iso, pais) VALUES ('FK', 'Islas Malvinas');
INSERT INTO cannabis.paises (iso, pais) VALUES ('MP', 'Islas Marianas del Norte');
INSERT INTO cannabis.paises (iso, pais) VALUES ('MA', 'Marruecos');
INSERT INTO cannabis.paises (iso, pais) VALUES ('MH', 'Islas Marshall');
INSERT INTO cannabis.paises (iso, pais) VALUES ('MQ', 'Martinica');
INSERT INTO cannabis.paises (iso, pais) VALUES ('MU', 'Mauricio');
INSERT INTO cannabis.paises (iso, pais) VALUES ('MR', 'Mauritania');
INSERT INTO cannabis.paises (iso, pais) VALUES ('YT', 'Mayotte');
INSERT INTO cannabis.paises (iso, pais) VALUES ('MX', 'Mexico');
INSERT INTO cannabis.paises (iso, pais) VALUES ('FM', 'Micronesia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('MD', 'Moldavia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('MC', 'Monaco');
INSERT INTO cannabis.paises (iso, pais) VALUES ('MN', 'Mongolia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('MS', 'Montserrat');
INSERT INTO cannabis.paises (iso, pais) VALUES ('MZ', 'Mozambique');
INSERT INTO cannabis.paises (iso, pais) VALUES ('MM', 'Myanmar');
INSERT INTO cannabis.paises (iso, pais) VALUES ('NA', 'Namibia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('NR', 'Nauru');
INSERT INTO cannabis.paises (iso, pais) VALUES ('NP', 'Nepal');
INSERT INTO cannabis.paises (iso, pais) VALUES ('NI', 'Nicaragua');
INSERT INTO cannabis.paises (iso, pais) VALUES ('NE', 'Níger');
INSERT INTO cannabis.paises (iso, pais) VALUES ('NG', 'Nigeria');
INSERT INTO cannabis.paises (iso, pais) VALUES ('NU', 'Niue');
INSERT INTO cannabis.paises (iso, pais) VALUES ('NF', 'Isla Norfolk');
INSERT INTO cannabis.paises (iso, pais) VALUES ('NO', 'Noruega');
INSERT INTO cannabis.paises (iso, pais) VALUES ('NC', 'Nueva Caledonia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('NZ', 'Nueva Zelanda');
INSERT INTO cannabis.paises (iso, pais) VALUES ('OM', 'Omán');
INSERT INTO cannabis.paises (iso, pais) VALUES ('NL', 'Paises Bajos');
INSERT INTO cannabis.paises (iso, pais) VALUES ('PK', 'Pakistan');
INSERT INTO cannabis.paises (iso, pais) VALUES ('PW', 'Palau');
INSERT INTO cannabis.paises (iso, pais) VALUES ('PS', 'Palestina');
INSERT INTO cannabis.paises (iso, pais) VALUES ('PA', 'Panama');
INSERT INTO cannabis.paises (iso, pais) VALUES ('PG', 'Papua Nueva Guinea');
INSERT INTO cannabis.paises (iso, pais) VALUES ('PY', 'Paraguay');
INSERT INTO cannabis.paises (iso, pais) VALUES ('PE', 'Peru');
INSERT INTO cannabis.paises (iso, pais) VALUES ('PN', 'Islas Pitcairn');
INSERT INTO cannabis.paises (iso, pais) VALUES ('PF', 'Polinesia Francesa');
INSERT INTO cannabis.paises (iso, pais) VALUES ('PL', 'Polonia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('PT', 'Portugal');
INSERT INTO cannabis.paises (iso, pais) VALUES ('PR', 'Puerto Rico');
INSERT INTO cannabis.paises (iso, pais) VALUES ('QA', 'Qatar');
INSERT INTO cannabis.paises (iso, pais) VALUES ('GB', 'Reino Unido');
INSERT INTO cannabis.paises (iso, pais) VALUES ('RE', 'Reunión');
INSERT INTO cannabis.paises (iso, pais) VALUES ('RW', 'Ruanda');
INSERT INTO cannabis.paises (iso, pais) VALUES ('RO', 'Rumania');
INSERT INTO cannabis.paises (iso, pais) VALUES ('RU', 'Rusia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('EH', 'Sahara Occidental');
INSERT INTO cannabis.paises (iso, pais) VALUES ('SB', 'Islas Salomón');
INSERT INTO cannabis.paises (iso, pais) VALUES ('WS', 'Samoa');
INSERT INTO cannabis.paises (iso, pais) VALUES ('AS', 'Samoa Americana');
INSERT INTO cannabis.paises (iso, pais) VALUES ('KN', 'San Cristóbal y Nevis');
INSERT INTO cannabis.paises (iso, pais) VALUES ('SM', 'San Marino');
INSERT INTO cannabis.paises (iso, pais) VALUES ('PM', 'San Pedro y Miquelón');
INSERT INTO cannabis.paises (iso, pais) VALUES ('VC', 'San Vicente y las Granadinas');
INSERT INTO cannabis.paises (iso, pais) VALUES ('SH', 'Santa Helena');
INSERT INTO cannabis.paises (iso, pais) VALUES ('LC', 'Santa Lucia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('ST', 'Santo Tome y Príncipe');
INSERT INTO cannabis.paises (iso, pais) VALUES ('SN', 'Senegal');
INSERT INTO cannabis.paises (iso, pais) VALUES ('CS', 'Serbia y Montenegro');
INSERT INTO cannabis.paises (iso, pais) VALUES ('SC', 'Seychelles');
INSERT INTO cannabis.paises (iso, pais) VALUES ('SL', 'Sierra Leona');
INSERT INTO cannabis.paises (iso, pais) VALUES ('SG', 'Singapur');
INSERT INTO cannabis.paises (iso, pais) VALUES ('SY', 'Siria');
INSERT INTO cannabis.paises (iso, pais) VALUES ('SO', 'Somalia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('LK', 'Sri Lanka');
INSERT INTO cannabis.paises (iso, pais) VALUES ('SZ', 'Suazilandia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('ZA', 'Sudafrica');
INSERT INTO cannabis.paises (iso, pais) VALUES ('SD', 'Sudan');
INSERT INTO cannabis.paises (iso, pais) VALUES ('SE', 'Suecia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('CH', 'Suiza');
INSERT INTO cannabis.paises (iso, pais) VALUES ('SR', 'Surinam');
INSERT INTO cannabis.paises (iso, pais) VALUES ('SJ', 'Svalbard y Jan Mayen');
INSERT INTO cannabis.paises (iso, pais) VALUES ('TH', 'Tailandia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('TW', 'Taiwan');
INSERT INTO cannabis.paises (iso, pais) VALUES ('TZ', 'Tanzania');
INSERT INTO cannabis.paises (iso, pais) VALUES ('TJ', 'Tayikistan');
INSERT INTO cannabis.paises (iso, pais) VALUES ('IO', 'Territorio Británico del Oceano Indico');
INSERT INTO cannabis.paises (iso, pais) VALUES ('TF', 'Territorios Australes Franceses');
INSERT INTO cannabis.paises (iso, pais) VALUES ('TL', 'Timor Oriental');
INSERT INTO cannabis.paises (iso, pais) VALUES ('TG', 'Togo');
INSERT INTO cannabis.paises (iso, pais) VALUES ('TK', 'Tokelau');
INSERT INTO cannabis.paises (iso, pais) VALUES ('TO', 'Tonga');
INSERT INTO cannabis.paises (iso, pais) VALUES ('TT', 'Trinidad y Tobago');
INSERT INTO cannabis.paises (iso, pais) VALUES ('TN', 'Tunez');
INSERT INTO cannabis.paises (iso, pais) VALUES ('TC', 'Islas Turcas y Caicos');
INSERT INTO cannabis.paises (iso, pais) VALUES ('TM', 'Turkmenistan');
INSERT INTO cannabis.paises (iso, pais) VALUES ('TR', 'Turquia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('TV', 'Tuvalu');
INSERT INTO cannabis.paises (iso, pais) VALUES ('UA', 'Ucrania');
INSERT INTO cannabis.paises (iso, pais) VALUES ('UG', 'Uganda');
INSERT INTO cannabis.paises (iso, pais) VALUES ('UY', 'Uruguay');
INSERT INTO cannabis.paises (iso, pais) VALUES ('UZ', 'Uzbekistan');
INSERT INTO cannabis.paises (iso, pais) VALUES ('VU', 'Vanuatu');
INSERT INTO cannabis.paises (iso, pais) VALUES ('VE', 'Venezuela');
INSERT INTO cannabis.paises (iso, pais) VALUES ('VN', 'Vietnam');
INSERT INTO cannabis.paises (iso, pais) VALUES ('VG', 'Islas Virgenes Britanicas');
INSERT INTO cannabis.paises (iso, pais) VALUES ('VI', 'Islas Virgenes de los Estados Unidos');
INSERT INTO cannabis.paises (iso, pais) VALUES ('WF', 'Wallis y Futuna');
INSERT INTO cannabis.paises (iso, pais) VALUES ('YE', 'Yemen');
INSERT INTO cannabis.paises (iso, pais) VALUES ('DJ', 'Yibuti');
INSERT INTO cannabis.paises (iso, pais) VALUES ('ZM', 'Zambia');
INSERT INTO cannabis.paises (iso, pais) VALUES ('ZW', 'Zimbabue');