INSERT INTO cannabis.variedades (id, id_tipo, id_pais, nombre, tiempo_floracion, interior, exterior, thc, cbd, genetica, description, file) VALUES (10, 1, 1, 'Full Melt Madness', 56, 0, 1, 38.00, 15.00, 'Pura', 'A sweet and fruity Afghani hybrid that is easy to grow, easy to clone, resistant to pests and powdery and as the name suggests she makes some awesome bubble hash. Nice relaxing after dinner smoke. Good sea of green plant. Medium green buds with orange hairs.', null);
INSERT INTO cannabis.variedades (id, id_tipo, id_pais, nombre, tiempo_floracion, interior, exterior, thc, cbd, genetica, description, file) VALUES (11, 1, 1, 'Obsidian Ice', 67, 1, 0, 30.00, 15.00, 'DSB x Snow Lotus F1', 'Obsidian Ice is the first hybrid we have worked with at House of Funk that shows fairly consistent purple phenotypes throughout. For style points, this plant highlights a reasonably stable, naturally branching growth pattern and medium sized purple tinged flowers, making Obsidian Ice one jaw-droppingly gorgeous plant. Iced over with a coating of heavy resins on top of dense flowers, this DSB Black Afghan hybrid also produces a staggering, nearly offensive odor (trust us, it’s a good thing). In order to avoid having a hybrid that is all style and no substance, we have also tested Obsidian Ice to have some of the most obliterating narcotic effects of any of the indica dominant hybrids we offer. Your mother told you to never walk across black ice; but if you come upon Obsidian Ice... the only danger is running out.', null);
INSERT INTO cannabis.variedades (id, id_tipo, id_pais, nombre, tiempo_floracion, interior, exterior, thc, cbd, genetica, description, file) VALUES (12, 4, 47, 'IMPA Ruderalis', 90, 0, 1, 20.00, 50.00, 'China x Rubina', 'Diese seltsame Blattform entstand aus einer Kreuzung zwichen einer aus CHINA stammenden RUDERALIS (mit ungewöhnlich grossen Blättern, die eher wie HINDUKUSH ausgesehen hat und vom Typ einer SATIVA entsprach) und meiner RUBINA, ebenso mit großen Blättern und vom Wuchs INDICA. Daraus selektierten wir einige Kirschblättrige Nachkommen, deren Aussehen stark an Asiatisches Springkraut erinnerte.

Rötliche bis lilafarbenden Stängel, große, ungefingerte Blätter und ein erstaunliches, rasantes Wachstum. Mit Automatik-Eigenschaften, aber im Aussehen wie eine tropische Pflanze.', null);
INSERT INTO cannabis.variedades (id, id_tipo, id_pais, nombre, tiempo_floracion, interior, exterior, thc, cbd, genetica, description, file) VALUES (14, 6, 113, 'Amnesia Haze', 84, 1, 0, 20.00, 16.00, 'Afghani Hawaiian x Laos x Jamaica', 'Amnesia Haze is one of the finest Hazes Soma Seeds has to offer. The smell and taste are unforgettable, until you smoke it and forget everything!', null);
INSERT INTO cannabis.variedades (id, id_tipo, id_pais, nombre, tiempo_floracion, interior, exterior, thc, cbd, genetica, description, file) VALUES (15, 6, 6, 'alexsander', 33, 1, 0, 33.00, 21.00, 'dsdsd', 'sdasdasdasdasd', null);
INSERT INTO cannabis.variedades (id, id_tipo, id_pais, nombre, tiempo_floracion, interior, exterior, thc, cbd, genetica, description, file) VALUES (16, 6, 121, 'Hawaiian Snow', 77, 1, 0, 18.37, 0.59, 'Hawai x Laos', 'Effect: very well known between heavy smokers that look for strong buds. A sativa-high that creeps on you, followed by a blasting stoned feeling.
Flowering indoor: 11 weeks with a yield up to 700 gr/sqm.
Flowering outdoor: ready between October and November in the Northern hemisphere. In June in the Southern one. Voted best weed of 2003, a true sativa champion for champion growers. Yield up to 1200 gr/plant.', null);
INSERT INTO cannabis.variedades (id, id_tipo, id_pais, nombre, tiempo_floracion, interior, exterior, thc, cbd, genetica, description, file) VALUES (18, 6, 211, 'Green House Thai', 98, 1, 0, 10.00, 0.50, 'Thai X Laos', 'Effect: Extremely high and introspective experience. woody flavour, very complex

Flowering indoor: 13 to 15 weeks with a yield of 500-600 gr/sqm. Tall plant with long internode. ideal for scrog and lst.

Flowering outdoor: It finishes in december in the Northern Hemisphere or June in the Southern. Production up to 800 gr. per plant.', null);
INSERT INTO cannabis.variedades (id, id_tipo, id_pais, nombre, tiempo_floracion, interior, exterior, thc, cbd, genetica, description, file) VALUES (19, 6, 18, 'Arjan''s Ultra Haze #2', 88, 0, 1, 22.90, 1.10, 'Neville`s Haze, Mango Haze, Laos.', 'Effect: great psychoactive high, strong and long lasting. Very uplifting and social, it leaves a very relaxing feeling thanks to the high CBD. Fruity and woody sativa taste.
Flowering indoor: 12-13 weeks with a yield of 700-800 gr/sqm.
Flowering outdoor: finishes by mid November in the Northern hemisphere, or by mid June in the Southern. Production can reach 1000 gr/plant. Long buds with loads of resin.', null);
INSERT INTO cannabis.variedades (id, id_tipo, id_pais, nombre, tiempo_floracion, interior, exterior, thc, cbd, genetica, description, file) VALUES (21, 4, 146, 'Lowryder', 20, 1, 0, 10.00, 0.50, 'Williams Wonder / Northern Lights No. 2 / Mexican Ruderalis', 'Small, hardy, autoflowering strain, small yields.

Aptly named for its low profile (both literally and figuratively), Lowryder was developed for extreme rapid growth (life cycle is 8 weeks from seed to bud), uniquely short height, and amazingly versatile. 

Lowryder is stable and reliable in its properties, a product of nine generations of selective breeding, and is non-deviant and hermaphrodite-free. Lowryder claims direct descendance from superior Williams Wonder and Northern Lights no.2 indica, as well as a more exotic, virtually unknown short variety believed to be descended from "Mexican Ruderalis", an experimental cross created over 25 years ago.

Passing directly from the seedling to the flowering stage, Lowryder altogether does away with the vegetative growth stage, in a process called autoflowering. In other words, when planted, it sprouts, grows a couple sets of leaves, then immediately and automatically begins flowering (males at about day 17, females at day 20). As a result, it is the quickest, most compact, and most discrete plant available.

Having no vegetative stage, Lowryder can not be cloned or regenerated, for all intents and purposes. Replanting seeds is a must. But then, this plants unique advantages do away with any reason for cloning in the first place. It is an ideal parent strain, producing some offspring with its unique autoflowering traits.

To complement its unique characteristics, Lowryders final appearance, taste, and high, have nothing to envy of the finer weed varieties, an excellent strain with high potency and good resin production.

See also Mdanzig Seeds

', null);
INSERT INTO cannabis.variedades (id, id_tipo, id_pais, nombre, tiempo_floracion, interior, exterior, thc, cbd, genetica, description, file) VALUES (22, 4, 3, 'izarhaze', 2, 1, 0, 12.00, 27.00, 'dsdsd', 'sddad', null);
INSERT INTO cannabis.variedades (id, id_tipo, id_pais, nombre, tiempo_floracion, interior, exterior, thc, cbd, genetica, description, file) VALUES (23, 7, 3, 'joanhaze', 33, 0, 1, 16.00, 12.00, 'hhh', 'dsdad', null);
INSERT INTO cannabis.variedades (id, id_tipo, id_pais, nombre, tiempo_floracion, interior, exterior, thc, cbd, genetica, description, file) VALUES (25, 5, 6, 'Critikal', 12, 0, 1, 2.00, 45.00, 'sdasdas', 'sddasd', null);
INSERT INTO cannabis.variedades (id, id_tipo, id_pais, nombre, tiempo_floracion, interior, exterior, thc, cbd, genetica, description, file) VALUES (26, 6, 7, 'Automatic', 55, 1, 0, 10.00, 5.00, 'lll', 'hj', null);
INSERT INTO cannabis.variedades (id, id_tipo, id_pais, nombre, tiempo_floracion, interior, exterior, thc, cbd, genetica, description, file) VALUES (28, 6, 8, 'Bubble Crack', 33, 0, 1, 20.00, 10.00, 'hgghfg', 'fhjh', null);
INSERT INTO cannabis.variedades (id, id_tipo, id_pais, nombre, tiempo_floracion, interior, exterior, thc, cbd, genetica, description, file) VALUES (29, 3, 6, 'Auto Parmesan', 20, 1, 0, 20.00, 30.00, 'gh', 'gh', null);
INSERT INTO cannabis.variedades (id, id_tipo, id_pais, nombre, tiempo_floracion, interior, exterior, thc, cbd, genetica, description, file) VALUES (30, 5, 17, 'Orient Express', 30, 0, 1, 10.00, 0.20, 'ertgyh', 'fgghh', null);
INSERT INTO cannabis.variedades (id, id_tipo, id_pais, nombre, tiempo_floracion, interior, exterior, thc, cbd, genetica, description, file) VALUES (32, 2, 63, 'Vietnam Tourist Hemp', 20, 0, 1, 20.00, 12.00, 'ghj', 'gyhhjk', null);
INSERT INTO cannabis.variedades (id, id_tipo, id_pais, nombre, tiempo_floracion, interior, exterior, thc, cbd, genetica, description, file) VALUES (33, 4, 1, 'Black Forrest', 355, 1, 0, 10.00, 30.00, 'dfsf', 'h', null);
INSERT INTO cannabis.variedades (id, id_tipo, id_pais, nombre, tiempo_floracion, interior, exterior, thc, cbd, genetica, description, file) VALUES (35, 1, 11, 'EXPLOSION', 20, 1, 0, 10.00, 20.00, 'fgjhhkj', 'jhjj', null);
INSERT INTO cannabis.variedades (id, id_tipo, id_pais, nombre, tiempo_floracion, interior, exterior, thc, cbd, genetica, description, file) VALUES (36, 3, 6, 'pepe', 32, 1, 0, 2.00, 2.00, 'sddsd', 'dsdsd', null);